---
output: github_document
---

```{r default, include = FALSE, collapse = TRUE}
library(knitr)
opts_chunk$set(prompt = TRUE, comment = "")
```

## Analysis of survival data with cure fraction and variable selection: A pseudo-observations approach

This repository contains example codes used to data analyses reported in the manuscript 
"Analysis of survival data with cure fraction and variable selection: A pseudo-observations approach".

The proposed pseudo-observation technique is demonstrated through applications to the following two datasets.

  - [A melanoma data](https://htmlpreview.github.io/?https://github.com/stc04003/pseudo-cure/blob/main/Examples/e1684.html) consists of the following demonstrations.
    - Fitting a mixture cure model with an EM-based approach
    - Fitting a mixture cure model with with the proposed pseudo-observation approach
    - Fitting a bounded cumulative hazard model with with the proposed pseudo-observation approach 
    - Computing and plotting pseudo-residuals
  
  - [A dental data](https://htmlpreview.github.io/?https://github.com/stc04003/pseudo-cure/blob/main/Examples/teeth.html) consists of the following demonstrations.
    - Fitting a mixture cure model with with the proposed pseudo-observation approach
    - Fitting a bounded cumulative hazard model with with the proposed pseudo-observation approach 
    - Variable selection with a penalized generalized estimating equations approach